language: generic
sudo: required
dist: trusty

cache:
  - directories:
    - "$HOME/emacs"

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
env:
  global:
    - EMAKE_SHA1=1b23379eb5a9f82d3e2d227d0f217864e40f23e0
  matrix:
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=26.1 MELPA_STABLE=true
    - EMACS_VERSION=snapshot

before_install:
  - wget "https://raw.githubusercontent.com/vermiculus/emake.el/${EMAKE_SHA1}/emake.mk"
  - make setup

install:
  - make install

script:
  - make compile
  - make test-ert

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
